-- MySQL Script generated by MySQL Workbench
-- Wed May 27 11:28:20 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema banco_rh
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema banco_rh
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `banco_rh` DEFAULT CHARACTER SET utf8 ;
USE `banco_rh` ;

-- -----------------------------------------------------
-- Table `banco_rh`.`Empresa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `banco_rh`.`Empresa` ;

CREATE TABLE IF NOT EXISTS `banco_rh`.`Empresa` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `cnpj` VARCHAR(14) NOT NULL,
  `nome` VARCHAR(50) NOT NULL,
  `telefone` VARCHAR(20) NULL DEFAULT NULL,
  `email` VARCHAR(100) NOT NULL,
  `endereco` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idEmpresa_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `cnpj_UNIQUE` (`cnpj` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `banco_rh`.`Vaga`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `banco_rh`.`Vaga` ;

CREATE TABLE IF NOT EXISTS `banco_rh`.`Vaga` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_empresa` BIGINT UNSIGNED NOT NULL,
  `cargo` VARCHAR(60) NOT NULL,
  `descricao` TEXT NOT NULL,
  `status` ENUM('Aberta', 'Fechada', 'Suspensa', 'Pausada') NOT NULL,
  `qtd_vagas` INT NULL DEFAULT 1,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idVagas_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_Vaga_Empresa_idx` (`id_empresa` ASC) VISIBLE,
  CONSTRAINT `fk_Vaga_Empresa`
    FOREIGN KEY (`id_empresa`)
    REFERENCES `banco_rh`.`Empresa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `banco_rh`.`Candidato`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `banco_rh`.`Candidato` ;

CREATE TABLE IF NOT EXISTS `banco_rh`.`Candidato` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(110) NOT NULL,
  `cpf` VARCHAR(11) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `telefone` VARCHAR(20) NOT NULL,
  `pretensao_salarial` DECIMAL(10,2) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `banco_rh`.`Funcionario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `banco_rh`.`Funcionario` ;

CREATE TABLE IF NOT EXISTS `banco_rh`.`Funcionario` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `cpf` VARCHAR(11) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `telefone` VARCHAR(20) NULL DEFAULT NULL,
  `cargo` VARCHAR(50) NOT NULL,
  `salario` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `banco_rh`.`Experiencia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `banco_rh`.`Experiencia` ;

CREATE TABLE IF NOT EXISTS `banco_rh`.`Experiencia` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome_experiencia` VARCHAR(100) NOT NULL,
  `categoria` VARCHAR(50) NULL DEFAULT NULL,
  `descricao_experiencia` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `banco_rh`.`Candidato_Experiencia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `banco_rh`.`Candidato_Experiencia` ;

CREATE TABLE IF NOT EXISTS `banco_rh`.`Candidato_Experiencia` (
  `Candidato_id` BIGINT UNSIGNED NOT NULL,
  `Experiencia_id` BIGINT UNSIGNED NOT NULL,
  INDEX `fk_Candidato_has_Experiencia_Experiencia1_idx` (`Experiencia_id` ASC) VISIBLE,
  INDEX `fk_Candidato_has_Experiencia_Candidato1_idx` (`Candidato_id` ASC) VISIBLE,
  CONSTRAINT `fk_Candidato_has_Experiencia_Candidato1`
    FOREIGN KEY (`Candidato_id`)
    REFERENCES `banco_rh`.`Candidato` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Candidato_has_Experiencia_Experiencia1`
    FOREIGN KEY (`Experiencia_id`)
    REFERENCES `banco_rh`.`Experiencia` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `banco_rh`.`Candidatura`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `banco_rh`.`Candidatura` ;

CREATE TABLE IF NOT EXISTS `banco_rh`.`Candidatura` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_candidato` BIGINT UNSIGNED NOT NULL,
  `id_vaga` BIGINT UNSIGNED NOT NULL,
  `data_interesse` DATE NOT NULL,
  `etapa_atual` ENUM('Triagem', 'Avaliacao', 'Fechamento') NOT NULL,
  `resultado_final` ENUM('Aprovado', 'Reprovado') NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `cod_unico_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_Candidatura_Candidato1_idx` (`id_candidato` ASC) VISIBLE,
  INDEX `fk_Candidatura_Vaga1_idx` (`id_vaga` ASC) VISIBLE,
  CONSTRAINT `fk_Candidatura_Candidato1`
    FOREIGN KEY (`id_candidato`)
    REFERENCES `banco_rh`.`Candidato` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Candidatura_Vaga1`
    FOREIGN KEY (`id_vaga`)
    REFERENCES `banco_rh`.`Vaga` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `banco_rh`.`Entrevista`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `banco_rh`.`Entrevista` ;

CREATE TABLE IF NOT EXISTS `banco_rh`.`Entrevista` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_funcionario` BIGINT UNSIGNED NOT NULL,
  `id_candidatura` BIGINT UNSIGNED NOT NULL,
  `data_hora` DATETIME NOT NULL,
  `nota` DECIMAL(5,2) NULL DEFAULT NULL,
  `avaliacao_final` TEXT NULL DEFAULT NULL,
  `ordem_etapa` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_Entrevista_Funcionario1_idx` (`id_funcionario` ASC) VISIBLE,
  INDEX `fk_Entrevista_Candidatura1_idx` (`id_candidatura` ASC) VISIBLE,
  CONSTRAINT `fk_Entrevista_Funcionario1`
    FOREIGN KEY (`id_funcionario`)
    REFERENCES `banco_rh`.`Funcionario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Entrevista_Candidatura1`
    FOREIGN KEY (`id_candidatura`)
    REFERENCES `banco_rh`.`Candidatura` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `banco_rh`.`Contratacao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `banco_rh`.`Contratacao` ;

CREATE TABLE IF NOT EXISTS `banco_rh`.`Contratacao` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_candidatura` BIGINT UNSIGNED NOT NULL,
  `data_inicio` DATE NOT NULL,
  `data_rescisao` DATE NULL DEFAULT NULL,
  `dias_garantia` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_Contratacao_Candidatura1_idx` (`id_candidatura` ASC) VISIBLE,
  CONSTRAINT `fk_Contratacao_Candidatura1`
    FOREIGN KEY (`id_candidatura`)
    REFERENCES `banco_rh`.`Candidatura` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
